workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: latest
      java: 11 # Or a version compatible with your Gradle setup

    trigger:
      branch: master
      # You can also trigger on tags or pull requests

    scripts:
      - name: Set up Flutter
        script: | 
          flutter channel stable
          flutter upgrade
          flutter doctor

      - name: Get Flutter dependencies
        script: | 
          flutter pub get

      - name: Build Android Appbundle
        script: | 
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/**/*.aab
      - build/app/outputs/apk/**/*.apk

    publishing:
      # Add your publishing integrations here (e.g., Google Play, Firebase App Distribution)
      # For example:
      # google_play:
      #   track: alpha
      #   service_account_key: | # Encrypted in Codemagic UI
      #     $GOOGLE_PLAY_SERVICE_ACCOUNT_KEY
      #   changes_not_sent_for_review: true


